### ISSUE TITLE
Creating remote instances is not as fast as it could be

### ISSUE THREAD

**Issue by psorowka** [bheisen/vrpc#12] opened 2020-08-18 13:01 UTC
It has been observed, that creating many (> 100) remote instances of objects with VRPC takes much longer than expected. We have measured latencies of around 400-800ms per instance in a test setup. By looking through the code and the timings, the following performance improvement points have been identified:

- use QoS 0 instead of QoS 1. On a developer laptop (i7) with a local, anonymous broker, we see 10..20ms in flight time for QoS 1 and only 1..2ms for QoS 0
- combine subscriptions for member functions at least into a single SUBSCRIBE packet but much better use wildcards
- switch the order of publish/subscribe after instance creation

With that, the latency problems of 800ms can be reduced to <15ms.

**Comment by bheisen** [comment] 2020-10-30 13:22
The issue is addressed in two ways:

1. Subscription is now using wildcarding
2. OoS 0 setting is optionally possible

**Closed by bheisen** 2020-10-30 13:22 UTC
